package com.eugene.entity;
// Generated Mar 27, 2018 9:14:42 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.eugene.util.Navigatable;

/**
 * If7EntryRst generated by hbm2java
 */

@Entity(name = "EntryRst")
@IdClass(value = EntryRstId.class)
@Table(name = "IF7_ENTRY_RST", schema = "TAKION79")
public class EntryRst implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String entryId;
	private String settleId;
	private short entrySeq;
	private String gocId;
	private BigDecimal entryResult;
	private int seq;

	public EntryRst() {
	}

	@Id
	@Column(name = "BASE_DATE", nullable = false, length = 8)
	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;
	}

	@Id
	@Column(name = "ENTRY_ID", nullable = false, length = 20)
	public String getEntryId() {
		return this.entryId;
	}

	public void setEntryId(String entryId) {
		this.entryId = entryId;
	}

	@Id
	@Column(name = "SETTLE_ID", nullable = false, length = 20)
	public String getSettleId() {
		return this.settleId;
	}

	public void setSettleId(String settleId) {
		this.settleId = settleId;
	}

	@Id
	@Column(name = "ENTRY_SEQ", nullable = false, precision = 4, scale = 0)
	public short getEntrySeq() {
		return this.entrySeq;
	}

	public void setEntrySeq(short entrySeq) {
		this.entrySeq = entrySeq;
	}

	@Column(name = "GOC_ID", length = 20)
	public String getGocId() {
		return this.gocId;
	}

	public void setGocId(String gocId) {
		this.gocId = gocId;

	}

	@Column(name = "ENTRY_RESULT", scale = 4)
	public BigDecimal getEntryResult() {
		return this.entryResult;
	}

	public void setEntryResult(BigDecimal entryResult) {
		this.entryResult = entryResult;

	}

	/**
	 * idString
	 * @return String
	 */
	@Transient
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getEntryId());
		buffer.append("#").append(getSettleId());
		buffer.append("#").append(getEntrySeq());

		String rst = buffer.toString();

		return rst;
	}

	@Transient
	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntryRst))
			return false;
		EntryRst castOther = (EntryRst) other;

		return this.idString().equals(castOther.idString());
	}

	@Transient
	public int getSeq() {
		return seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	@Transient
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getEntryId() == null ? 0 : this.getEntryId().hashCode());
		result = 37 * result + (getSettleId() == null ? 0 : this.getSettleId().hashCode());
		result = 37 * result + this.getEntrySeq();
		return result;
	}

}
