package com.eugene.entity;
// Generated Mar 27, 2018 9:14:42 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugene.util.Navigatable;

/**
 * If7EntryRstId generated by hbm2java
 */

public class EntryRstId implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String entryId;
	private String settleId;
	private short entrySeq;

	public EntryRstId() {
	}

	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;

	}

	public String getEntryId() {
		return this.entryId;
	}

	public void setEntryId(String entryId) {
		this.entryId = entryId;

	}

	public String getSettleId() {
		return this.settleId;
	}

	public void setSettleId(String settleId) {
		this.settleId = settleId;

	}

	public short getEntrySeq() {
		return this.entrySeq;
	}

	public void setEntrySeq(short entrySeq) {
		this.entrySeq = entrySeq;

	}

	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getEntryId());
		buffer.append("#").append(getSettleId());
		buffer.append("#").append(getEntrySeq());

		String rst = buffer.toString();

		return rst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntryRstId))
			return false;
		EntryRstId castOther = (EntryRstId) other;

		return ((this.getBaseDate() == castOther.getBaseDate())
				|| (this.getBaseDate() != null && castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getEntryId() == castOther.getEntryId())
						|| (this.getEntryId() != null && castOther.getEntryId() != null && this.getEntryId().equals(castOther.getEntryId())))
				&& ((this.getSettleId() == castOther.getSettleId())
						|| (this.getSettleId() != null && castOther.getSettleId() != null && this.getSettleId().equals(castOther.getSettleId())))
				&& (this.getEntrySeq() == castOther.getEntrySeq());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getEntryId() == null ? 0 : this.getEntryId().hashCode());
		result = 37 * result + (getSettleId() == null ? 0 : this.getSettleId().hashCode());
		result = 37 * result + this.getEntrySeq();
		return result;
	}

}
