package com.eugene.entity;
// Generated Mar 27, 2018 9:14:42 PM by Hibernate Tools 5.2.0.CR1 with Custom Template_takion!!!!!! 

import javax.persistence.Id;
import javax.persistence.Transient;
import com.eugene.util.Navigatable;

/**
 * If7SettleRstId generated by hbm2java
 */

public class SettleRstId implements java.io.Serializable, Navigatable {

	private String baseDate;
	private String gocId;
	private String settleId;
//	private SettleMst settleMst;

	public SettleRstId() {
	}

	public String getBaseDate() {
		return this.baseDate;
	}

	public void setBaseDate(String baseDate) {
		this.baseDate = baseDate;

	}

	public String getGocId() {
		return this.gocId;
	}

	public void setGocId(String gocId) {
		this.gocId = gocId;

	}

	public String getSettleId() {
		return this.settleId;
	}

	public void setSettleId(String settleId) {
		this.settleId = settleId;

	}
	
	/**
	 * idString
	 * @return String
	 */
	public String idString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("#").append(getBaseDate());
		buffer.append("#").append(getGocId());
		buffer.append("#").append(getSettleId());
//		buffer.append("#").append(getSettleMst().getSettleId());

		String rst = buffer.toString();

		return rst;
	}

//	public SettleMst getSettleMst() {
//		return settleMst;
//	}
//
//	public void setSettleMst(SettleMst settleMst) {
//		this.settleMst = settleMst;
//	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SettleRstId))
			return false;
		SettleRstId castOther = (SettleRstId) other;

		return ((this.getBaseDate() == castOther.getBaseDate())
				|| (this.getBaseDate() != null && castOther.getBaseDate() != null && this.getBaseDate().equals(castOther.getBaseDate())))
				&& ((this.getGocId() == castOther.getGocId()) || (this.getGocId() != null && castOther.getGocId() != null && this.getGocId().equals(castOther.getGocId())))
				&& ((this.getSettleId() == castOther.getSettleId())
						|| (this.getSettleId() != null && castOther.getSettleId() != null && this.getSettleId().equals(castOther.getSettleId())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBaseDate() == null ? 0 : this.getBaseDate().hashCode());
		result = 37 * result + (getGocId() == null ? 0 : this.getGocId().hashCode());
		result = 37 * result + (getSettleId() == null ? 0 : this.getSettleId().hashCode());
		return result;
	}

}
